-- MySQL Script generated by MySQL Workbench
-- Thu May  9 17:11:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pw2024_tubes_233040085
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pw2024_tubes_233040085` ;

-- -----------------------------------------------------
-- Schema pw2024_tubes_233040085
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pw2024_tubes_233040085` DEFAULT CHARACTER SET utf8 ;
USE `pw2024_tubes_233040085` ;

-- -----------------------------------------------------
-- Table `pw2024_tubes_233040085`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pw2024_tubes_233040085`.`user` ;

CREATE TABLE IF NOT EXISTS `pw2024_tubes_233040085`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(225) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `status` TINYINT NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pw2024_tubes_233040085`.`genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pw2024_tubes_233040085`.`genre` ;

CREATE TABLE IF NOT EXISTS `pw2024_tubes_233040085`.`genre` (
  `idgenre` INT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pw2024_tubes_233040085`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pw2024_tubes_233040085`.`movie` ;

CREATE TABLE IF NOT EXISTS `pw2024_tubes_233040085`.`movie` (
  `id_movie` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  `release_year` YEAR NULL,
  `rating` DECIMAL NULL,
  `movie_trailer` VARCHAR(225) NULL,
  `age_rating` VARCHAR(5) NULL,
  `writer` VARCHAR(225) NULL,
  `director` VARCHAR(225) NULL,
  `actor` TEXT NULL,
  `picture` VARCHAR(225) NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `genre_idgenre` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`id_movie`),
  INDEX `fk_movie_genre_idx` (`genre_idgenre` ASC) VISIBLE,
  INDEX `fk_movie_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_movie_genre`
    FOREIGN KEY (`genre_idgenre`)
    REFERENCES `pw2024_tubes_233040085`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movie_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `pw2024_tubes_233040085`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
